-- Produtos (TCustomProduto) sincronizados do PrimeStart (P2S) — painel em
-- /admin/operacional/produtos. Tabela larga: TODOS os 115 campos escalares
-- reais da classe (confirmados empiricamente em 515 produtos de produção
-- em 2026-08-10) viram coluna própria; Precos e InfosItemEstoque (arrays
-- aninhados de verdade, um-para-muitos) viram jsonb. Os outros 10 arrays
-- da classe (Fornecedores, Componentes/kit, ConfigLojasVirtuais etc.) não
-- entram — testados e vazios/não usados em praticamente 100% do catálogo.
--
-- p2s_oid é a chave de upsert. Campos de referência (Categoria, Marca...)
-- guardam o oid cru (ex: "P,518") na coluna original, mais um "_nome"
-- resolvido só para Categoria/SubCategoria/Marca (os mais úteis pra
-- busca/filtro na tela) — os demais (centros de custo/receita fiscais)
-- ficam só como oid cru.
create table if not exists produtos (
  id bigserial primary key,
  p2s_oid text not null unique,
  altura numeric,
  bloqueia_edicao_ficha_detalha_comp_kit boolean,
  cest text,
  cnpj_fabricante text,
  cofins_cst_padrao text,
  cofins_cst_padrao_exp text,
  cofins_cst_padrao_exp_sn text,
  cofins_cst_padrao_imp text,
  cofins_cst_padrao_sn text,
  cofins_pct_aliquota_padrao numeric,
  cofins_pct_aliquota_padrao_exp numeric,
  cofins_tipo_calculo_padrao numeric,
  cofins_tipo_calculo_padrao_exp numeric,
  campo_adicional1 text,
  campo_adicional2 text,
  categoria text,
  categoria_especial text,
  centro_custo_compra text,
  centro_custo_rel_compra_nfe text,
  centro_receita_locacao text,
  centro_receita_venda text,
  classificacao_fiscal text,
  codigo numeric,
  codigo_anvisa text,
  codigo_barras text,
  codigo_exibicao text,
  codigo_fabricante text,
  codigo_formatado text,
  comprimento numeric,
  custo_reposicao numeric,
  custo_reposicao_dolar numeric,
  data_cadastro date,
  data_ult_mov_entrada_compra date,
  data_ultima_alteracao_cadastro date,
  data_validade_codigo_anvisa date,
  depr_disponibiliza_como_kit boolean,
  descricao_detalhada text,
  disponibilizar_como_kit boolean,
  excecao_fiscal numeric,
  fator_conversao numeric,
  fatura_como_servico boolean,
  flag_amostrador boolean,
  flag_em_desuso boolean,
  foto text,
  grade_gerada boolean,
  habilitado_para_locacao boolean,
  habilitado_para_venda boolean,
  icms_base_calculo_icms text,
  icms_csosn_padrao text,
  icms_csosn_padrao_exp text,
  icms_csosn_padrao_imp text,
  icms_cst_padrao text,
  icms_cst_padrao_exp text,
  icms_cst_padrao_imp text,
  icms_ipi_entra_na_base_de_calculo boolean,
  icms_ipi_entra_na_base_de_calculo_st boolean,
  icms_modalidade_bc numeric,
  icms_modalidade_bc_exp numeric,
  icms_modalidade_bc_st numeric,
  icms_modalidade_bc_st_exp numeric,
  icms_pct_cred_sn numeric,
  icms_pct_icms numeric,
  icms_pct_icms_imp numeric,
  icms_pct_margem_valor_adic_st numeric,
  icms_pct_margem_valor_adic_st_exp numeric,
  icms_sujeito_fcp boolean,
  icms_usa_pct_cred_sn_especifica boolean,
  ii_pct_ii numeric,
  ipi_cst_padrao text,
  ipi_cst_padrao_imp text,
  ipi_pct_ipi numeric,
  item_estoque_pai_grade text,
  largura numeric,
  login_cadastro text,
  login_ultima_alteracao_cadastro text,
  marca text,
  modelo text,
  motivo_isencao_anvisa text,
  nome_estoque_ult_mov_entrada_compra text,
  nome_item text,
  num_dias_indisponivel_apos_ret_loc numeric,
  num_dimensoes_grade numeric,
  observacoes text,
  origem_nfe numeric,
  pis_cst_padrao text,
  pis_cst_padrao_exp text,
  pis_cst_padrao_exp_sn text,
  pis_cst_padrao_imp text,
  pis_cst_padrao_sn text,
  pis_pct_aliquota_padrao numeric,
  pis_pct_aliquota_padrao_exp numeric,
  pis_tipo_calculo_padrao numeric,
  pis_tipo_calculo_padrao_exp numeric,
  permite_recarga_controle_ind_fracionado boolean,
  peso_unitario numeric,
  possui_excecao_fiscal boolean,
  produzido_escala_relevante text,
  situacao_tributaria text,
  situacao_tributaria_pdv text,
  sub_categoria text,
  sub_centro_custo_compra text,
  sub_centro_custo_rel_compra_nfe text,
  sub_centro_receita_locacao text,
  sub_centro_receita_venda text,
  tem_controle_ind_fracionado boolean,
  tem_controle_individual boolean,
  tem_seguro numeric,
  unidade text,
  unidade_exportacao text,
  usa_csts_do_cadastro_nfe_importacao boolean,
  utiliza_unidade_diferente_nf_exportacao boolean,
  categoria_nome text,
  sub_categoria_nome text,
  marca_nome text,
  precos jsonb,
  estoques jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists produtos_codigo_idx on produtos (codigo);
create index if not exists produtos_categoria_nome_idx on produtos (categoria_nome);
create index if not exists produtos_marca_nome_idx on produtos (marca_nome);

alter table produtos disable row level security;
